import { DisplayLine, Scene } from '@/app/types';
import Button from '@/components/Button';
import HelpLabel from '@/components/Help';
import { useTooltip } from '@/components/Tooltip';
import { PlusIcon } from '@heroicons/react/24/outline';
import { useState } from 'react';
import { useEditorProject } from '../../../../EditorContext';
import { useScene } from '../../SceneContext';
import ScriptLine from './ScriptLine';

export function ScriptSection() {
  const { scene, isStartingScene } = useScene();
  const { updateProject } = useEditorProject();
  const { showTooltip, hideTooltip } = useTooltip();
  const script = scene.script || [];
  const [draggedIndex, setDraggedIndex] = useState<number | null>(null);
  const [dropIndex, setDropIndex] = useState<number | null>(null);

  const handleUpdateScene = (updates: Partial<Scene>) => {
    updateProject(
      (draft) => {
        const sceneIndex = draft.cartridge.scenes.findIndex((s) => s.uuid === scene.uuid);
        if (sceneIndex !== -1) {
          draft.cartridge.scenes[sceneIndex] = {
            ...draft.cartridge.scenes[sceneIndex],
            ...updates,
          };
        }
      },
      {
        message: 'updated scene script',
        context: JSON.stringify({ sceneId: scene.uuid, updates }),
      },
    );
  };

  const handleRemoveLine = (index: number) => {
    const updatedScript = script.filter((_, i) => i !== index);
    handleUpdateScene({ script: updatedScript });
  };

  const handleAddLine = () => {
    const newLine: DisplayLine = {
      type: 'narration',
      text: '',
      characterName: undefined,
      metadata: {
        verbatim: true,
      },
    };
    handleUpdateScene({ script: [...script, newLine] });
  };

  const handleReorderScript = (fromIndex: number, toIndex: number) => {
    if (fromIndex === toIndex) return;

    const newScript = [...script];
    const [movedItem] = newScript.splice(fromIndex, 1);
    newScript.splice(toIndex, 0, movedItem);

    handleUpdateScene({ script: newScript });
  };

  const handleDragStart = (index: number) => {
    setDraggedIndex(index);
  };

  const handleDragEnd = () => {
    if (draggedIndex !== null && dropIndex !== null) {
      handleReorderScript(draggedIndex, dropIndex);
    }
    setDraggedIndex(null);
    setDropIndex(null);
  };

  const handleDragOver = (index: number, position: 'before' | 'after') => {
    if (draggedIndex !== null) {
      const targetIndex = position === 'before' ? index : index + 1;
      if (targetIndex !== draggedIndex && targetIndex !== draggedIndex + 1) {
        setDropIndex(targetIndex);
      }
    }
  };

  const handleDragLeave = () => {
    setDropIndex(null);
  };

  return (
    <div>
      <div
        className={`flex sticky top-[-20px] justify-between bg-white dark:bg-slate-900 items-center z-[2] pt-4 pb-2`}
      >
        <HelpLabel
          label="Opening script"
          tips={[
            {
              type: 'public',
              tooltip:
                'Occurs exactly as written at the start of the scene. Every line after is generated by the AI narrator.',
            },
          ]}
        />
        <Button
          variant="icon"
          onClick={handleAddLine}
          onMouseOver={() => showTooltip('Add a new script line')}
          onMouseOut={hideTooltip}
        >
          <PlusIcon className="w-4 h-4" />
        </Button>
      </div>

      {/* Script Lines */}
      <div className="flex flex-col gap-2">
        {script.length === 0 ? (
          <div className="text-slate-500 dark:text-slate-400 italic bg-slate-50 dark:bg-slate-900 border border-slate-300 dark:border-slate-700 rounded-lg p-4">
            No opening script, so the AI narrator will start the scene for you.
            {isStartingScene
              ? ' Recommended: Use this to explain the goal of the game to the player.'
              : ''}
          </div>
        ) : undefined}
        {script.map((line, index) => (
          <div key={index} className="relative">
            {/* Drop indicator line before */}
            {dropIndex === index && draggedIndex !== null && (
              <div className="absolute top-0 left-0 right-0 h-0.5 bg-blue-500 z-[1]" />
            )}

            {/* Drop zone before */}
            <div
              className="absolute -top-2 left-0 right-0 h-4 z-[2]"
              onDragOver={(e) => {
                e.preventDefault();
                handleDragOver(index, 'before');
              }}
              onDragLeave={handleDragLeave}
              onDrop={(e) => {
                e.preventDefault();
                handleDragEnd();
              }}
            />

            <ScriptLine
              line={line}
              scene={scene}
              lineIndex={index}
              onRemove={() => handleRemoveLine(index)}
              onDragStart={() => handleDragStart(index)}
              onDragEnd={handleDragEnd}
              isDragging={draggedIndex === index}
            />

            {/* Drop zone after (only for last item) */}
            {index === script.length - 1 && (
              <>
                {/* Drop indicator line after last item */}
                {dropIndex === script.length && draggedIndex !== null && (
                  <div className="absolute -bottom-1 left-0 right-0 h-0.5 bg-blue-500 z-[1]" />
                )}
                <div
                  className="absolute -bottom-2 left-0 right-0 h-4 z-[2]"
                  onDragOver={(e) => {
                    e.preventDefault();
                    handleDragOver(index, 'after');
                  }}
                  onDragLeave={handleDragLeave}
                  onDrop={(e) => {
                    e.preventDefault();
                    handleDragEnd();
                  }}
                />
              </>
            )}
          </div>
        ))}
      </div>
    </div>
  );
}
